language: node_js
sudo: false
node_js:
  - "stable"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database diary;' -U postgres
script:
  - npm test
after_success:
- npm run coverage
sudo: false
