language: node_js
sudo: false
node_js:
  - "stable"
install:
  - cd server && npm install
script:
  - npm test
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
after_success: coveralls
